name: anaconda-client-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - anaconda-client
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
      - -r requirements.txt
